server:
  port: 9000
mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  profiles:
    active: dev
  application:
    name: bcpcs-file
  rabbitmq:
      host: 192.168.110.212
      port: 5672
      username: admin
      password: admin
      # 开启发送失败退回
      publisher-returns: true
      listener:
        simple:
          retry:
            enabled: false #消费者端的重试
          acknowledge-mode: manual         # 开启ACK
          auto-startup: true  #启动时自动启动容器	true
  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        service-id: BCPCS-CONFIG
#        enabled: true
#      label: ${spring.profiles.active}
#      profile: ${spring.profiles.active}
#      username: admin
#      password: admin
  #redis配置
  datasource:
    url: jdbc:mysql://192.168.110.212:3306/cxf?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  druid:
    initialSize: 5 #初始化连接大小
    minIdle: 5     #最小连接池数量
    maxActive: 20  #最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 from DUAL  #测试连接
    testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
    filters: stat,wall,log4j #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录

  redis:
    host: 192.168.110.212
    password:
    port: 6379
    database: 0
    timeout: 30000
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@192.168.110.212:8761/eureka/
  instance:
      prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
swagger:
  title: bcpcs-file
  description: file manager

file:
  path: /home/cloud/file/
  down: open


